### ISSUE TITLE
As a user, I would like to know how many approvals a pending PR already has

### ISSUE THREAD

**Issue by bhargavrpatel** [pullreminders/backlog#43]
**Context**
Currently, we are getting pull reminders for PRs we created with a mention of the author (i.e:`Waiting on @barco`). However, our process requires 2 approvals prior to a PR being merged. Currently, this information is missed in the reminder message that is posted on the channel.

**Suggestion**
Add an option to expose this field or make that a default. Perhaps we can even let the admins add the number of reviews required (if Github does not allow that to be pulled in) which would then let you say something like '1/2' on the title of the PR.

P.S: Thanks.

Edit: Formatting.

**Comment by abinoda** [comment]
@bhargavrpatel Thanks for submitting! Let me confirm to make sure I am understanding correctly...

1. Your team's GitHub workflow is "2 approvals to merge" and you are using GitHub's [required approvals feature](https://help.github.com/articles/about-required-reviews-for-pull-requests/), correct?
2. The problem is that right now, as soon as one approval is submitted, the reminders start pinging the author even though the PR is still waiting for another review, correct?

Also, which org are you with that's using Pull Reminders?

**Comment by bhargavrpatel** [comment]
You are correct. I am from Unata (instacart)

Regards,
Bhargav

**Comment by abinoda** [comment]
@bhargavrpatel Cool, I am going to try and have this done in the next few days. Thank you very much for writing this up!

**Comment by bhargavrpatel** [comment]
Awesome. Appreciate the help.

**Comment by abinoda** [comment]
@bhargavrpatel Question - would the workflow be better if Pull Reminders did NOT @mention the author at all, and instead just showed the number of reviews/approvals? Does it mislead or create confusion?

Note that feature of nudging the author was moreso designed for teams using review requests where you can determine with certainty that a PR is waiting on an author vs reviewer.

**Comment by bhargavrpatel** [comment]
If we want to make sure someone gets _nudged_ you can say "authored by:" and @mention the author and along with the fact that it still required N reviews.

> Note that feature of nudging the author was moreso designed for teams using review requests where you can determine with certainty that a PR is waiting on an author vs reviewer.
Noted. Yeah in this case, I think the proposed feature would be an additional check that is introduced and adding more certainty; i.e: if it has N/N reviews, it is definitely waiting on an author.

**Comment by abinoda** [comment]
@bhargavrpatel Rather than trying to calculate how many approvals are required, could I just display how many approvals the PR has in the reminder? This would require less configuration and I hope still address your use case?

The reason I am proposing this is that there are so many different granular settings that determine how many approvals are required, and since it isn't provided by the API, it'd be very difficult for me to accurately compute:

<img width="736" alt="screen shot 2018-06-12 at 8 55 28 am" src="https://user-images.githubusercontent.com/50083/41294750-72af85e6-6e1e-11e8-95ea-3cbb2fdb05ca.png">

**Comment by bhargavrpatel** [comment]
Certainly. That actually might be better in the cases where above settings are set to a lower number than the required. For example, we've set that count to 1 but generally prefer 2 reviews; allowing merges on 1 reviews if the diff is very small.

**Comment by abinoda** [comment]
@bhargavrpatel I just released this – let me know how it works for you and if you have any feedback.

FYI – I also made an update so that "Waiting on @author" isn't printed since the logic for that is only accurate when teams are using review requests.

**Comment by abinoda** [comment]
@bhargavrpatel Also, I liked your suggestion below and plan on making this an option you can turn on. But I think its best to have it turned off by default so people do not get annoyed:

> If we want to make sure someone gets nudged you can say "authored by:" and @mention the author

**Comment by bhargavrpatel** [comment]
Awesome. Can’t wait to try it tomorrow. Thanks!

**Comment by bhargavrpatel** [comment]
Closed the issue as its resolved. Thank you once again @abinoda! We just saw it in action as well.

**Comment by abinoda** [comment]
@bhargavrpatel Cool! Also, after talking to GitHub there *is* a way for the approval count to be 100% consistent with the "required reviews" rules e.g., when a review is automatically dismissed due to a new commit. So I will push another update in a couple days so to improve the accuracy. Letting you know in case you spot any edge cases.
