### ISSUE TITLE
As a user, I want to be able to filter team reminders based on who the author or reviewer is

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#51]
# Problem

From @mbyio:

> There are some repos that my team shared with other teams, and we don't have a good way to only get reminders for PRs that are relevant to our team; I wish there was a way to have a whitelist so people will only be notified if someone on the whitelist created the PR or was requested as a reviewer

From @lfre:

> We have multiple teams working on the same repo, so having all messages go to a single room is not really helpful and rather spammy.

# Proposed solution

Add a new dropdown filter that excludes PRs from reminders unless they are waiting on an author or reviewer who is a member of one of the selected GitHub teams. **When this filter is active, PR's waiting on reviews from members of *other* teams will not be included in the reminders.**

<img width="1191" alt="screen shot 2018-06-24 at 7 57 45 pm" src="https://user-images.githubusercontent.com/50083/41825091-e7e4ea4e-77e8-11e8-8aec-8a7e48e33cb9.png">

**Comment by abinoda** [comment]
@lev-kazakov Let me know if this is the same issue you're encountering or not!

**Comment by abinoda** [comment]
@damonpetta @incognito @jchavarri @bleedsy @austinh @james-pack @TheFrozenFire @peteyoung I'm curious to know if this is an issue you've run into and whether the proposed solution would address it.

**Comment by abinoda** [comment]
This is released!

**Comment by mbyio** [comment]
Thanks! I'll see if we can try it out this week.

**Comment by cobrabr** [comment]
I haven't had this happen yet, because we're piloting PullReminders with a single team, but it will definitely be a requirement when more teams are added to the fold. 

Also, along the same lines, it would be interesting to be able to limit the reminders to PRs created by specific authors and/or PRs for which specific individuals are assigned as reviewers (so that, for example, my team doesn't get reminders about PRs created by other teams and/or PRs for which the individuals assigned as reviewers aren't on my team).

**Comment by FloraSaysGoodmorning** [comment]
Nice! Would be even better if we can have mandatory reviews and optional reviewers:)
