### ISSUE TITLE
As a user, I want to filter reminders based on PR staleness

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#60]
From @xinzweb:

> Thanks a lot for adding `staleness` to the reminder. My next request would be adding 'staleness` to the Filters of the reminder. Today, I can only filter on the `Age` of the PR, but I actually want to filter on the `Staleness` of the PR. This will reduce the list size, and only highlight the PR that's stale, so that people can focus on them. Thoughts?

**Comment by majormoses** [comment]
I agree about the value of the feature, in the mean time what I have been doing (and will probably still do) for the orgs I maintain is to use labels to filter out `Status: Awaiting Response` and when the user either updates the code or responds on the PR the reviewer will get an email alert and can decide if the PR is ready to review again (and be reminded on) or if its still a WIP.

**Comment by abinoda** [comment]
I agree with this proposal. I'd like to confirm however that this feature is specifically for open-source. On closed-source teams I don't think PRs pile up as much or get as stale to the point where a filter would be necessary.

@bootstraponline @johannasmith @tas50 Would this feature help you for open-source? Do you agree with what I said about it not having as much value for closed-source?

**Comment by majormoses** [comment]
> I'd like to confirm however that this feature is specifically for open-source. On closed-source teams I don't think PRs pile up as much or get as stale to the point where a filter would be necessary.

Not sure I agree it's only for OSS, my current job I see lots of PRs that are stale, I certainly think it offers more value to OSS projects but I think it has benefits for larger organizations as well. My non OSS org is ~175 people, ~75 teams, ~300 repos, and our current number of open PRs is 835. I can't imagine that all of those are up to date and only a handful of them really need to be open. In some ways because it is not OSS (which usually has a limited number of highly technical maintainers) I can't exactly force that many people (with varying skill sets) across all those teams to use proper tagging, so staleness would probably be a better way of handling it for us. Also in most OSS projects its OK for the initial reviewer to stick with it until its merged even if they are gone for a few days. In businesses depending on the criticality of the work that may not be the case.

**Comment by bootstraponline** [comment]
> Would this feature help you for open-source? Do you agree with what I said about it not having as much value for closed-source?

I think the feature is equally valuable for open source & closed source. With that said, we try to merge all PRs quickly. In Slack, we are displaying all PRs (except for WIP and POC). I personally wouldn't use the feature however if we had a large amount of unmerged PRs then I see the value.

**Comment by johannaratliff** [comment]
I would definitely filter by staleness if it was available. If it's getting regularly commented on or addressed, I don't feel like the team needs to get pinged on it again. Can't speak to closed source maintenance from my end.

**Comment by abinoda** [comment]
@tas50 I know you're still chugging through your backlog but would you +1 this from an open-source usage perspective?

**Comment by tas50** [comment]
It would be nice to filter on staleness so we can focus our energy on current PRs. Like @majormoses we use a label when we're awaiting a response from the user. In the ideal world we'd have a better setup than that.

**Comment by abinoda** [comment]
@xinzweb @bootstraponline @tas50 @majormoses @johannasmith Thanks all for the feedback. I'll get this implemented soon!

**Comment by abinoda** [comment]
@xinzweb @tas50 @majormoses @johannasmith I've released this feature 🚀 Please let me know how it works for you!

CC'ing some other OSS maintainers: @danrabbit @kitsunet @bkeepers @terminalmage @gtmanfred @damacus @hiimbex @wilhelmklopp @JasonEtco
