### ISSUE TITLE
Question: Is there a way to add a user who has not yet committed anything

### ISSUE THREAD

**Issue by davidgoate** [pullreminders/backlog#77]
# Scenario

New joiner comes, we set up all accounts, add to GitHub etc etc...

When it comes to pull reminders, even though the user is part of our organisation on GitHub, we cannot see them as a user to add on pull reminders `Onboard users` screen. My hunch is maybe they will only show up once they actually commit code or make a PR. But this is a slight annoyance, we have to remember to come back and do this later - it's smoother if it's part f our on-boarding workflow as just another step that gets done right away.

**Comment by abinoda** [comment]
@davidgoiate Hmmm. Pull Reminders uses GitHub webooks to import new organization members in real-time. I believe the issue is this: when you add a new member, they don't actually become a member until that user "Accepts" their invitation to your org. So I'm guessing when you visited the `Onboard users` screen the user had not yet accepted the invite. Let me know if this theory sounds applicable and whether you're seeing the user on that page now.

**Comment by davidgoate** [comment]
@abinoda thanks. I think you might be right - it seems to be fine. Thanks for the advice.
